apiVersion: v2
name: synology-cert-updater
description: A Helm chart for the Synology Certificate Updater application
type: application
version: 0.1.0
appVersion: "latest" # Corresponds to the image tag used by default
