# Default values for synology-cert-updater.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Configuration for the target Synology NAS
synology:
  # -- Hostname or IP address and port of the Synology NAS API (e.g., your-nas.local:5001 or 192.168.1.100:5001)
  host: ""
  # -- Synology username for authentication. Required if secrets.existingCredentialsSecretName is not set.
  username: ""
  # -- Synology password for authentication. Required if secrets.existingCredentialsSecretName is not set.
  password: ""

# -- Configuration for Kubernetes Secrets used by the chart
secrets:
  # -- Name of the Kubernetes TLS secret containing the certificate and key to upload (e.g., my-tls-secret)
  certificate: ""
  # -- Name of the Kubernetes Secret to store Synology credentials. Used only if existingCredentialsSecretName is empty.
  # The actual name used in templates defaults to RELEASE_NAME-synology-credentials if this is not set.
  credentials: "" # Default name is generated in templates if needed
  # -- Name of an existing Kubernetes Secret containing Synology credentials. If set, the chart will not create its own credentials secret.
  # The existing secret must contain keys named 'host', 'username', and 'password'.
  existingCredentialsSecretName: ""

# -- Configuration for the one-off Kubernetes Job
job:
  # -- Enable the creation of a Kubernetes Job for immediate execution.
  enabled: true
  # -- Run the update process in dry-run mode (simulate changes without applying them).
  dryRun: false

# -- Configuration for the scheduled Kubernetes CronJob
cronJob:
  # -- Kubernetes CronJob schedule (e.g., "0 2 * * *"). If set, a CronJob is created instead of a Job (unless job.enabled is also true).
  schedule: ""
  # -- Run the update process in dry-run mode (simulate changes without applying them).
  dryRun: false
  # -- Deadline in seconds for starting the job if it misses its scheduled time.
  startingDeadlineSeconds: null
  # -- Concurrency policy for the CronJob (Allow, Forbid, Replace).
  concurrencyPolicy: Allow
  # -- Number of successful finished jobs to retain.
  successfulJobsHistoryLimit: 3
  # -- Number of failed finished jobs to retain.
  failedJobsHistoryLimit: 1

# -- Common settings applicable to both Job and CronJob pods
commonJobSettings:
  # -- Pattern to identify the certificate on the Synology NAS to update (e.g., "*.example.com", "synology.my.domain")
  domainPattern: ""
  # -- Time-to-live in seconds after the Job finishes (completed or failed). Automatically cleans up finished Jobs.
  ttlSecondsAfterFinished: 3600 # 1 hour
  # -- Restart policy for the pod within the Job/CronJob (Never, OnFailure).
  restartPolicy: Never
  # -- Optional backoff limit for failed pods within a Job.
  backoffLimit: 4

# -- Container image configuration
image:
  # -- Container image repository
  repository: ghcr.io/liofal/synology-cert-updater
  # -- Container image pull policy
  pullPolicy: IfNotPresent
  # -- Container image tag (defaults to the chart's appVersion)
  tag: ""

# -- Pod resource requests and limits
# @default -- No requests or limits set
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 200m
  #   memory: 256Mi

# -- Node selector configuration for pod assignment
# @default -- Pods can be scheduled on any node
nodeSelector: {}

# -- Tolerations for pod scheduling to allow scheduling onto nodes with matching taints
# @default -- No tolerations
tolerations: []

# -- Affinity configuration for pod scheduling
# @default -- No affinity rules
affinity: {}
