apiVersion: batch/v1
kind: CronJob
metadata:
  name: synology-cert-update-cron
spec:
  schedule: "0 0 1 * *"  # Run at midnight on the first day of each month
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # Auto-delete job 24h after completion
      template:
        spec:
          serviceAccountName: synology-cert-updater
          containers:
          - name: cert-updater
            image: ghcr.io/liofal/synology-cert-updater:latest
            imagePullPolicy: Always
            env:
            - name: SYNOLOGY_HOST
              valueFrom:
                secretKeyRef:
                  name: synology-credentials
                  key: host
            - name: SYNOLOGY_USER
              valueFrom:
                secretKeyRef:
                  name: synology-credentials
                  key: username
            - name: SYNOLOGY_PASS
              valueFrom:
                secretKeyRef:
                  name: synology-credentials
                  key: password
            - name: DOMAIN_PATTERN
              value: "*.liofal.net"
            - name: DRY_RUN
              value: "false"
            volumeMounts:
            - name: cert-volume
              mountPath: /certs
              readOnly: true
          volumes:
          - name: cert-volume
            secret:
              secretName: ingress-certmanager-tls
          restartPolicy: Never
