apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: synology-cert-reader
  namespace: downloads
subjects:
- kind: ServiceAccount
  name: synology-cert-updater
  namespace: ${DEPLOYMENT_NAMESPACE}  # This will be replaced by the script
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
