apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: downloads
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ingress-certmanager-tls"]
  verbs: ["get"]
