{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "synology-cert-updater.fullname" . }}-secret-reader
  labels:
    {{- include "synology-cert-updater.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ .Values.secrets.certificate | quote }}]
  verbs: ["get"]
{{- end }}
