{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "synology-cert-updater.fullname" . }}-secret-reader-binding
  labels:
    {{- include "synology-cert-updater.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "synology-cert-updater.serviceAccountName" . }}
  # ServiceAccount namespace is implicitly the same as RoleBinding namespace
roleRef:
  kind: Role
  name: {{ include "synology-cert-updater.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
