{{- if not .Values.secrets.existingCredentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.credentials | default (printf "%s-synology-credentials" .Release.Name) }}
  labels:
    {{- include "synology-cert-updater.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.synology.host | b64enc | quote }}
  username: {{ .Values.synology.username | b64enc | quote }}
  password: {{ .Values.synology.password | b64enc | quote }}
{{- end }}
