{{- if not .Values.secrets.existingCredentialsSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  # Use the fullname helper for the generated secret name if not overridden
  name: {{ include "synology-cert-updater.fullname" . }}-credentials
  labels:
    {{- include "synology-cert-updater.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ required "Synology host must be provided" .Values.synology.host | quote }}
  username: {{ required "Synology username must be provided" .Values.synology.username | quote }}
  password: {{ required "Synology password must be provided" .Values.synology.password | quote }}
{{- end -}}
